#!/usr/bin/with-contenv bash

mkdir "$PULSE_RUNTIME_PATH"
chmod 700 "$PULSE_RUNTIME_PATH"
chown "${USER}":"${USER}" "$PULSE_RUNTIME_PATH"

exec s6-setuidgid "${USER}" \
  /usr/bin/pulseaudio \
    --log-level=0 \
    --log-target=stderr \
    --exit-idle-time=-1 > /dev/null 2>&1
