site_name: Juno Innovations
site_description: Official documentation for Juno Innovations Helios - Building and customizing workstations
site_url: https://juno-innovations.com
repo_url: https://github.com/juno-fx/Helios
repo_name: juno-fx/Helios

theme:
  logo: assets/logos/helios/helios-logo-W-color.png  # Will need helios-light.png and helios-dark.png
  favicon: assets/logos/favicon/helios-icon.ico
  icon:
    repo: fontawesome/brands/github-alt
  name: material
  features:
    # Navigation
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.prune
    - navigation.sections
    - navigation.path
    - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    # Table of contents
    - toc.follow
    # Search
    - search.suggest
    - search.highlight
    - search.share
    # Content
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
    # UI
    - navigation.footer
    - navigation.top
    - header.autohide
  language: en
  palette:
    # Dark mode (default - listed first)
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Light mode
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font: false

plugins:
  - search:
      separator: '[\s\-\.]'
      lang:
        - en
  - literate-nav
  - termynal:
      title: zsh
      buttons: macos
      prompt_literal_start:
        - "$"

markdown_extensions:
  # Standard extensions
  - md_in_html
  - admonition
  - pymdownx.details
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
      title: On this page

  # PyMdown Extensions
  - pymdownx.blocks.caption
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Welcome:
      - index.md
  - Deployment:
      - Usage:
          - deploy-usage.md
      - Environments:
          - deploy-docker.md
          - deploy-compose.md
          - deploy-k8s.md
      - Persistence:
          - deploy-session.md
  - Building Workstations:
      - getting-started.md
      - Customization:
          - Packages:
            - package-management.md
            - Examples:
                - install-firefox.md
                - install-htop.md
          - Filesystem:
            - rootfs.md
            - Examples:
                - install-wallpaper.md
                - install-logo.md
          - Build Hooks:
            - build-hooks.md
            - Examples:
                - build-snap.md
                - build-theme.md
          - Event Hooks:
            - event-hooks.md
            - Examples:
                - event-idle.md
                - event-service.md
                - event-init.md
  - Contributing:
    - contributing.md
    - code-of-conduct.md
  - acknowledgements.md
  - Related Documentation:
    - related/related-docs.md

extra:
  generator: false
  #version:
  #  provider: mike  # Uncomment when mike is installed
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/juno-fx/
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/juno-innovations/about/
      name: LinkedIn
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/junoinnovations
      name: Docker Hub
  analytics:
    # Uncomment and add your Google Analytics ID when ready
    #provider: google
    #property: G-XXXXXXXXXX
    consent:
      title: Cookie consent
      description: >-
        We use cookies to recognize your repeated visits and preferences, as well
        as to measure the effectiveness of our documentation and whether users
        find what they're searching for. With your consent, you're helping us to
        make our documentation better.
      actions:
        - accept
        - reject
        - manage
  # SEO Meta tags
  meta:
    - name: description
      content: Official documentation for Juno Innovations Helios - Building and customizing workstations
    - name: keywords
      content: juno, innovations, helios, workstations, customization, docker, kubernetes
    - name: author
      content: Juno Innovations

copyright: |
  &copy; 2025 Juno Innovations. All rights reserved. | 
  <a href="#__consent">Change cookie settings</a> | 
  <a href="https://juno-fx.github.io/Orion-Documentation/">Orion Platform</a> | 
  <a href="https://juno-fx.github.io/Terra-Official-Plugins/">Terra Plugins</a>

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/theme-init.js
  - javascripts/extra.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js